# Generated by Django 2.0 on 2017-12-16 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationforcreditor',
            name='status',
            field=models.CharField(blank=True, choices=[('New', 'New status'), ('Sent', 'Sent status'), ('Received', 'Was viewed')], default='New', max_length=50),
        ),
    ]
