# Generated by Django 2.0 on 2017-12-13 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('rotation_start', models.DateTimeField()),
                ('rotation_end', models.DateTimeField()),
                ('name', models.CharField(max_length=200)),
                ('credit_type', models.CharField(max_length=100)),
                ('score_min', models.IntegerField()),
                ('score_max', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Creditor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='credit',
            name='creditor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creditor.Creditor'),
        ),
    ]
